### ISSUE TITLE
Reorder topics

### ISSUE THREAD

**Issue by romantseg** [RomanTsegelskyi/rbooks#1]

**Comment by chrisspruck** [comment]
I'd be happy to do this, but what kind of re-ordering are you considering? I think Beginner then Advanced is good, but then alphabetized after those, maybe?

**Comment by romantseg** [comment]
I am not sure myself, when I opened this issue, I just thought that it might be something worth thinking about. Alphabetization should be useful, do you have any other ideas?

**Comment by chrisspruck** [comment]
I do like Beginner then Advanced at the top of the list, so people who are new to R can spot those easily and first, so maybe as I suggested above, alphabetize after those two like:
-     Beginner Books
-    Advanced Books
  <hr>
-     Data Science
-     Machine Learning
-     R Development
-     Reports
-     Visualization

I'd also order the sections in the source the same way - as of now, Machine Learning comes after Data Science, although the ML link is before Data Science.

**Comment by romantseg** [comment]
Sure, that sounds good

**Comment by chrisspruck** [comment]
Sorry for all the clutter, but apparently GH won't delete anything. I had lots of trouble with the dividing line within the anchors, as it kept rendering differently inside the bulleted list vs. just below some text. Took it out entirely in the end.

**Comment by romantseg** [comment]
Looks great, thanks a lot!
